Expose parse_string and parse_file at top-level
chireiden/python-ass pull request #12
Opened 2020-10-07 11:42 UTC by denizdogan

I use parse_string way more often than parse_file, so I would suggest this change :)

2020-10-07 11:44 UTC, denizdogan commented
Forgot to expose parse_file and parse_string, but you get the gist :)

2020-10-22 07:34 UTC, hassaans approved these changes

2020-10-23 08:41 UTC, FichteFoll requested changes

2020-10-23 08:41 UTC, FichteFoll commented on ass/__init__.py
>  ]
You also need to adjust `__all__`.

2020-10-23 08:42 UTC, FichteFoll commented
I personally barely used `parse_string`, but I agree it's weird to only expose one of them. If people were to interact with `Document` more frequently, I'd say they are more likely to `from ass import Document` and then use `Document.parse_file`, but realistically most use cases will probably remain `import ass; ass.parse…`, so I think this is a fine addition.

2020-10-23 08:46 UTC, denizdogan commented
I think I deleted the branch where I put the PR and I can't figure out how to add to it now. If someone with commit access to this repo could just make these changes, I'd appreciate that. Otherwise, I'm going to have to make a new PR.

2020-10-23 09:00 UTC, FichteFoll commented
That's fine with me, I'll just leave this PR open as an issue.

2020-11-15 16:15 UTC, closed without merging